name: oauth_facebook
description: >
            Example showcasing facebook oauth Signup, Login and session management using jaguar_oauth
            and jaguar_auth
version: 0.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar: '>=0.4.0 <0.5.0'
  jaguar_reflect: '>=0.4.3 <0.5.0'
  jaguar_auth: '>=0.4.0 <0.5.0'
  jaguar_session: '>=0.4.1 <0.5.0'
  jaguar_oauth: '>=0.0.2 <0.1.0'
  jaguar_facebook_client: '>=0.0.4 <0.1.0'
  jaguar_oauth_facebook: '>=0.0.4 <0.1.0'
    # path: ../jaguar_oauth_facebook
  jaguar_serializer:
  jaguar_docstore:
  jaguar_mongo:
  mongo_dart:
  jaguar_serializer_mongo:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
